import { CosmeticItem } from "../types/cosmetics";

export const cosmeticItems: CosmeticItem[] = [
  // ── Accessories ──────────────────────────────────────────────────────────
  {
    id: "top-hat",
    name: "Top Hat",
    description: "A dapper look for a productive bunny",
    emoji: "🎩",
    pointsRequired: 15,
    type: "accessory",
  },
  {
    id: "pink-bow",
    name: "Pink Bow",
    description: "Cute and coordinated",
    emoji: "🎀",
    pointsRequired: 22,
    type: "accessory",
  },
  {
    id: "flower-crown",
    name: "Flower Crown",
    description: "Bloom with every completed task",
    emoji: "🌸",
    pointsRequired: 35,
    type: "accessory",
  },
  {
    id: "cool-shades",
    name: "Cool Shades",
    description: "Too cool for uncompleted tasks",
    emoji: "🕶️",
    pointsRequired: 50,
    type: "accessory",
  },
  {
    id: "wizard-hat",
    name: "Wizard Hat",
    description: "Channel your inner task wizard",
    emoji: "🪄",
    pointsRequired: 65,
    type: "accessory",
  },
  {
    id: "star-halo",
    name: "Star Halo",
    description: "You're shining bright",
    emoji: "⭐",
    pointsRequired: 85,
    type: "accessory",
  },
  {
    id: "crown",
    name: "Royal Crown",
    description: "For the ruler of all quests",
    emoji: "👑",
    pointsRequired: 110,
    type: "accessory",
  },

  // ── Fur Colours ──────────────────────────────────────────────────────────
  {
    id: "fur-pink",
    name: "Rosy Pink",
    description: "Soft and sweet",
    emoji: "🩷",
    pointsRequired: 25,
    type: "furColor",
    furColor: "#FFB3C6",
  },
  {
    id: "fur-grey",
    name: "Misty Grey",
    description: "Cool and mysterious",
    emoji: "🩶",
    pointsRequired: 45,
    type: "furColor",
    furColor: "#C8C8C8",
  },
  {
    id: "fur-golden",
    name: "Golden Glow",
    description: "Shiny as your achievements",
    emoji: "💛",
    pointsRequired: 70,
    type: "furColor",
    furColor: "#FFE066",
  },
  {
    id: "fur-blue",
    name: "Ocean Blue",
    description: "Calm, cool, and collected",
    emoji: "🩵",
    pointsRequired: 100,
    type: "furColor",
    furColor: "#87CEEB",
  },
  {
    id: "fur-midnight",
    name: "Midnight",
    description: "For the late-night quest master",
    emoji: "💜",
    pointsRequired: 150,
    type: "furColor",
    furColor: "#9B59B6",
  },

  // ── Backgrounds ──────────────────────────────────────────────────────────
  {
    id: "bg-mint",
    name: "Mint Garden",
    description: "A fresh and calming backdrop",
    emoji: "🌿",
    pointsRequired: 28,
    type: "background",
    bgColor: "#C8F7C5",
  },
  {
    id: "bg-lavender",
    name: "Lavender Dusk",
    description: "Soft, dreamy, and relaxing",
    emoji: "🪻",
    pointsRequired: 58,
    type: "background",
    bgColor: "#E8D5F5",
  },
  {
    id: "bg-ocean",
    name: "Ocean Breeze",
    description: "As calm as the open sea",
    emoji: "🌊",
    pointsRequired: 90,
    type: "background",
    bgColor: "#C5E8F7",
  },
  {
    id: "bg-sunset",
    name: "Sunset Glow",
    description: "Warm golden hour vibes",
    emoji: "🌅",
    pointsRequired: 125,
    type: "background",
    bgColor: "#FFE4C4",
  },
  {
    id: "bg-night",
    name: "Night Sky",
    description: "For the late-night achiever",
    emoji: "🌙",
    pointsRequired: 175,
    type: "background",
    bgColor: "#1E1E3F",
  },
];

export const accessoryItems = cosmeticItems.filter((item) => item.type === "accessory");
export const furColorItems = cosmeticItems.filter((item) => item.type === "furColor");
export const backgroundItems = cosmeticItems.filter((item) => item.type === "background");
