export type TaskPriority = "high" | "medium" | "low";

export type RecurrenceFrequency = "none" | "daily" | "weekly" | "monthly";

export type Task = {
  id: string;
  title: string;
  description: string;
  category: string;
  completed: boolean;
  priority: TaskPriority;
  dueDate: string; // ISO string or YYYY-MM-DD
  createdDate: string;
  reminderTime: string;
  estimatedMinutes: number;
  notificationId?: string | null;

  // --- New Recurring Task Fields ---
  recurrence?: RecurrenceFrequency; // "daily", "weekly", "monthly", or "none"/undefined
  isRecurringInstance?: boolean;    // Tracks if this is an instance generated by a repeating rule
  parentId?: string | null;         // Connects an instance back to its original "template" task
};
